-- =============================================================================
--   caso 1: sinonimos y permisos sobre objetos propios
-- =============================================================================

-- 1.7 sinonimos publicos para las tablas necesarias

CREATE OR REPLACE PUBLIC SYNONYM DEUDOR              FOR PRY2205_EFT.DEUDOR;
CREATE OR REPLACE PUBLIC SYNONYM TARJETA_DEUDOR      FOR PRY2205_EFT.TARJETA_DEUDOR;
CREATE OR REPLACE PUBLIC SYNONYM CUOTA_TARJETAS      FOR PRY2205_EFT.CUOTA_TARJETAS;
CREATE OR REPLACE PUBLIC SYNONYM OCUPACION           FOR PRY2205_EFT.OCUPACION;
CREATE OR REPLACE PUBLIC SYNONYM TRANSACCION_TARJETA_DEUDOR FOR PRY2205_EFT.TRANSACCION_TARJETA_DEUDOR;
CREATE OR REPLACE PUBLIC SYNONYM SUCURSAL            FOR PRY2205_EFT.SUCURSAL;
CREATE OR REPLACE PUBLIC SYNONYM T_ANALISIS_TARJETAS FOR PRY2205_EFT.T_ANALISIS_TARJETAS;
CREATE OR REPLACE PUBLIC SYNONYM SEQ_T_ANALISIS      FOR PRY2205_EFT.SEQ_T_ANALISIS;
CREATE OR REPLACE PUBLIC SYNONYM PAGOS_DEUDA         FOR PRY2205_EFT.PAGOS_DEUDA;
CREATE OR REPLACE PUBLIC SYNONYM FORMA_PAGO          FOR PRY2205_EFT.FORMA_PAGO;
CREATE OR REPLACE PUBLIC SYNONYM PESOS_VIP           FOR PRY2205_EFT.PESOS_VIP;
CREATE OR REPLACE PUBLIC SYNONYM TIPOS_DE_DEUDOR     FOR PRY2205_EFT.TIPOS_DE_DEUDOR;
CREATE OR REPLACE PUBLIC SYNONYM TIPO_TRANSACCION_TARJETA FOR PRY2205_EFT.TIPO_TRANSACCION_TARJETA;
CREATE OR REPLACE PUBLIC SYNONYM PRODUCTO            FOR PRY2205_EFT.PRODUCTO;
CREATE OR REPLACE PUBLIC SYNONYM COMUNA              FOR PRY2205_EFT.COMUNA;
CREATE OR REPLACE PUBLIC SYNONYM PROVINCIA           FOR PRY2205_EFT.PROVINCIA;
CREATE OR REPLACE PUBLIC SYNONYM REGION              FOR PRY2205_EFT.REGION;
CREATE OR REPLACE PUBLIC SYNONYM PARAM_AVANCES       FOR PRY2205_EFT.PARAM_AVANCES;
CREATE OR REPLACE PUBLIC SYNONYM RESUM_AVANCES_MES   FOR PRY2205_EFT.RESUM_AVANCES_MES;

-- sinonimo privado

CREATE OR REPLACE SYNONYM T_ANALISIS FOR PRY2205_EFT.T_ANALISIS_TARJETAS;
 
-- 1.8 permisos de objeto sobre las tablas (asignados al ROL, no al usuario)
-- se asignan al ROL para seguir el principio de menor privilegio y
-- facilitar la administracion: si cambia el usuario, solo se reasigna el rol
--
-- PRY2205_ROL_D (desarrollador): necesita SELECT en tablas del CASO 2
-- PRY2205_ROL_C (consultor):     necesita SELECT en tablas del CASO 2 y CASO 3
 
-- tablas requeridas para el caso 2 
GRANT SELECT ON DEUDOR              TO PRY2205_ROL_D;
GRANT SELECT ON TARJETA_DEUDOR      TO PRY2205_ROL_D;
GRANT SELECT ON CUOTA_TARJETAS      TO PRY2205_ROL_D;
GRANT SELECT ON OCUPACION           TO PRY2205_ROL_D;

GRANT SELECT ON DEUDOR                     TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON TARJETA_DEUDOR             TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON CUOTA_TARJETAS             TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON OCUPACION                  TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON TRANSACCION_TARJETA_DEUDOR TO PRY2205_EFT_DES WITH GRANT OPTION;
 
GRANT SELECT ON DEUDOR              TO PRY2205_ROL_C;
GRANT SELECT ON TARJETA_DEUDOR      TO PRY2205_ROL_C;
GRANT SELECT ON CUOTA_TARJETAS      TO PRY2205_ROL_C;
GRANT SELECT ON OCUPACION           TO PRY2205_ROL_C;
 
-- tablas requeridas para el caso 3
GRANT SELECT ON TRANSACCION_TARJETA_DEUDOR TO PRY2205_ROL_C;
GRANT SELECT ON SUCURSAL                   TO PRY2205_ROL_C;
GRANT SELECT ON T_ANALISIS_TARJETAS        TO PRY2205_ROL_C;
 
-- 1.9 creacion de tabla y secuencia para el caso 3
 
CREATE TABLE T_ANALISIS_TARJETAS (
    NUM_ANALISIS       NUMBER        NOT NULL,
    NRO_TARJETA        NUMBER(30)    NOT NULL,
    TOTAL_CUOTAS       NUMBER(2)     NOT NULL,
    MONTO_TOTAL_TRANSA NUMBER(10)    NOT NULL,
    FECHA_TRANSACCION  DATE          NOT NULL,
    DIRECCION          VARCHAR2(40)  NOT NULL,
    MONTO_REAJUSTADO   NUMBER        NOT NULL,
    CONSTRAINT T_ANALISIS_TARJETAS_PK PRIMARY KEY (NUM_ANALISIS)
);
 
CREATE SEQUENCE SEQ_T_ANALISIS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- =============================================================================
--  caso 3.1: carga de datos en T_ANALISIS_TARJETAS
-- =============================================================================

-- caso 3.1: INSERT usando SELECT
 
INSERT INTO T_ANALISIS_TARJETAS (
    NUM_ANALISIS,
    NRO_TARJETA,
    TOTAL_CUOTAS,
    MONTO_TOTAL_TRANSA,
    FECHA_TRANSACCION,
    DIRECCION,
    MONTO_REAJUSTADO
)
SELECT
    SEQ_T_ANALISIS.NEXTVAL,
    NRO_TARJETA,
    TOTAL_CUOTAS,
    MONTO_TOTAL_TRANSA,
    FECHA_TRANSACCION,
    DIRECCION,
    MONTO_REAJUSTADO
FROM (
    SELECT
        TTD.NRO_TARJETA                                        AS NRO_TARJETA,
        TTD.TOTAL_CUOTAS_TRANSACCION                           AS TOTAL_CUOTAS,
        TTD.MONTO_TOTAL_TRANSACCION                            AS MONTO_TOTAL_TRANSA,
        TTD.FECHA_TRANSACCION                                  AS FECHA_TRANSACCION,
        INITCAP(S.DIRECCION)                                   AS DIRECCION,
        ROUND(
            TTD.MONTO_TOTAL_TRANSACCION *
            CASE
                WHEN TTD.MONTO_TOTAL_TRANSACCION BETWEEN 200000 AND 300000 THEN 1.05
                WHEN TTD.MONTO_TOTAL_TRANSACCION BETWEEN 300001 AND 500000 THEN 1.07
                ELSE 1.00
            END
        )                                                      AS MONTO_REAJUSTADO
    FROM TRANSACCION_TARJETA_DEUDOR TTD
        INNER JOIN SUCURSAL S ON S.ID_SUCURSAL = TTD.ID_SUCURSAL
    WHERE UPPER(S.DIRECCION) LIKE 'A%'
      AND TTD.MONTO_TOTAL_TRANSACCION >= 200000
    ORDER BY TTD.NRO_TARJETA ASC, MONTO_REAJUSTADO DESC
);

COMMIT;

-- verificar resultado
SELECT * FROM T_ANALISIS_TARJETAS;
 
-- =============================================================================
--  caso 3.2: optimizacion con indices
-- =============================================================================
-- plan de ejecucion antes de crear indices
-- -----------------------------------------------------------------------
 
EXPLAIN PLAN FOR
SELECT
    TTD.NRO_TARJETA,
    TTD.TOTAL_CUOTAS_TRANSACCION,
    TTD.MONTO_TOTAL_TRANSACCION,
    TTD.FECHA_TRANSACCION,
    INITCAP(S.DIRECCION)  AS DIRECCION,
    ROUND(
        TTD.MONTO_TOTAL_TRANSACCION *
        CASE
            WHEN TTD.MONTO_TOTAL_TRANSACCION BETWEEN 200000 AND 300000 THEN 1.05
            WHEN TTD.MONTO_TOTAL_TRANSACCION BETWEEN 300001 AND 500000 THEN 1.07
            ELSE 1.00
        END
    ) AS MONTO_REAJUSTADO
FROM TRANSACCION_TARJETA_DEUDOR TTD
    INNER JOIN SUCURSAL S ON S.ID_SUCURSAL = TTD.ID_SUCURSAL
WHERE UPPER(S.DIRECCION) LIKE 'A%'
  AND TTD.MONTO_TOTAL_TRANSACCION >= 200000
ORDER BY TTD.NRO_TARJETA ASC, MONTO_REAJUSTADO DESC;
 
-- ver el plan antes de indices
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
 
-- -----------------------------------------------------------------------
-- se crean indices para mejorar el plan de ejecucion
-- -----------------------------------------------------------------------
 
CREATE INDEX IDX_SUC_DIRECCION
    ON SUCURSAL (DIRECCION);
 
CREATE INDEX IDX_TTD_MONTO
    ON TRANSACCION_TARJETA_DEUDOR (MONTO_TOTAL_TRANSACCION);
 
CREATE INDEX IDX_TTD_SUCURSAL
    ON TRANSACCION_TARJETA_DEUDOR (ID_SUCURSAL);
 
CREATE INDEX IDX_TTD_TARJETA
    ON TRANSACCION_TARJETA_DEUDOR (NRO_TARJETA);

-- -----------------------------------------------------------------------
-- plan de ejecucion despues de crear indices
-- -----------------------------------------------------------------------
 
EXPLAIN PLAN FOR
SELECT
    TTD.NRO_TARJETA,
    TTD.TOTAL_CUOTAS_TRANSACCION,
    TTD.MONTO_TOTAL_TRANSACCION,
    TTD.FECHA_TRANSACCION,
    INITCAP(S.DIRECCION)  AS DIRECCION,
    ROUND(
        TTD.MONTO_TOTAL_TRANSACCION *
        CASE
            WHEN TTD.MONTO_TOTAL_TRANSACCION BETWEEN 200000 AND 300000 THEN 1.05
            WHEN TTD.MONTO_TOTAL_TRANSACCION BETWEEN 300001 AND 500000 THEN 1.07
            ELSE 1.00
        END
    ) AS MONTO_REAJUSTADO
FROM TRANSACCION_TARJETA_DEUDOR TTD
    INNER JOIN SUCURSAL S ON S.ID_SUCURSAL = TTD.ID_SUCURSAL
WHERE UPPER(S.DIRECCION) LIKE 'A%'
  AND TTD.MONTO_TOTAL_TRANSACCION >= 200000
ORDER BY TTD.NRO_TARJETA ASC, MONTO_REAJUSTADO DESC;
 
-- ver el plan despues de indices
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);



