-- =============================================================================
--  caso 2: creacion de vista VW_ANALISIS_DEUDORES_PERIODO
-- =============================================================================
CREATE OR REPLACE VIEW VW_ANALISIS_DEUDORES_PERIODO AS
SELECT
    D.NUMRUN || '-' || D.DVRUN                                   AS RUT_DEUDOR,
    INITCAP(D.PNOMBRE) || ' ' ||
    INITCAP(D.APPATERNO) || ' ' ||
    INITCAP(D.APMATERNO)                                          AS NOMBRE_DEUDOR,
    CT.NRO_CUOTA_MAX                                              AS TOTAL_CUOTAS,
    ROUND(TTD.MONTO_TOTAL_TRANSACCION / CT.NRO_CUOTA_MAX)         AS PROMEDIO_VALOR_CUOTAS,
    TO_CHAR(MIN(CT.FECHA_VENC_CUOTA), 'DD/MM/YYYY')               AS FECHA_MAS_ANTIGUA,
    NVL(TO_CHAR(D.FONO_CONTACTO), 'Sin Informacion')              AS TELEFONO,
    UPPER(O.NOMBRE_PROF_OFIC)                                     AS OCUPACION,
    TD.CUPO_DISP_COMPRA                                           AS CUPO_DISP_COMPRA
FROM DEUDOR D
    INNER JOIN TARJETA_DEUDOR TD ON TD.NUMRUN = D.NUMRUN
    INNER JOIN TRANSACCION_TARJETA_DEUDOR TTD ON TTD.NRO_TARJETA = TD.NRO_TARJETA
    INNER JOIN (
        SELECT NRO_TARJETA, NRO_TRANSACCION,
               MAX(NRO_CUOTA)        AS NRO_CUOTA_MAX,
               MIN(FECHA_VENC_CUOTA) AS FECHA_VENC_CUOTA
        FROM CUOTA_TARJETAS
        WHERE FECHA_VENC_CUOTA >= TRUNC(ADD_MONTHS(SYSDATE, -12), 'YEAR')
          AND FECHA_VENC_CUOTA <  TRUNC(SYSDATE, 'YEAR')
        GROUP BY NRO_TARJETA, NRO_TRANSACCION
    ) CT ON CT.NRO_TARJETA = TD.NRO_TARJETA
        AND CT.NRO_TRANSACCION = TTD.NRO_TRANSACCION
    INNER JOIN OCUPACION O ON O.COD_OCUPACION = D.COD_OCUPACION
WHERE
    UPPER(O.NOMBRE_PROF_OFIC) != 'INGENIERO'
GROUP BY
    D.NUMRUN, D.DVRUN, D.PNOMBRE, D.APPATERNO, D.APMATERNO,
    D.FONO_CONTACTO, O.NOMBRE_PROF_OFIC, TD.CUPO_DISP_COMPRA,
    CT.NRO_CUOTA_MAX, TTD.MONTO_TOTAL_TRANSACCION, TTD.NRO_TRANSACCION
HAVING
    ROUND(TTD.MONTO_TOTAL_TRANSACCION / CT.NRO_CUOTA_MAX) < (
        SELECT MAX(ROUND(T2.MONTO_TOTAL_TRANSACCION / C2.NRO_CUOTA_MAX2))
        FROM TRANSACCION_TARJETA_DEUDOR T2
        INNER JOIN (
            SELECT NRO_TARJETA, NRO_TRANSACCION, MAX(NRO_CUOTA) AS NRO_CUOTA_MAX2
            FROM CUOTA_TARJETAS
            GROUP BY NRO_TARJETA, NRO_TRANSACCION
        ) C2 ON C2.NRO_TARJETA = T2.NRO_TARJETA
             AND C2.NRO_TRANSACCION = T2.NRO_TRANSACCION
        WHERE C2.NRO_CUOTA_MAX2 > 0
    )
ORDER BY CT.NRO_CUOTA_MAX ASC, TD.CUPO_DISP_COMPRA ASC;

GRANT SELECT ON VW_ANALISIS_DEUDORES_PERIODO TO PRY2205_EFT_CON;

SELECT * FROM VW_ANALISIS_DEUDORES_PERIODO;

